# -*- coding: utf-8 -*-
"""Random _Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2oa8T-s7XooEz0F_0f-BrSHNkR08ugX
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
import joblib

df = pd.read_csv('new_reduced.csv')
df

df['text'] = df['url'].fillna('') + ' ' + df['meta_title'].fillna('') + ' ' + df['meta_description'].fillna('')

X = df['text']
y = df['category_description']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = make_pipeline(
    TfidfVectorizer(
        tokenizer=lambda x: x.replace('.', ' ').replace('/', ' ').replace('-', ' ').split(),
        stop_words='english'
    ),
    RandomForestClassifier(n_estimators=100, random_state=42)
)


model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"Test Accuracy: {accuracy*100:.2f}%")


y_pred = model.predict(X_test)

results_df = pd.DataFrame({
    'Text': X_test.values,
    'Actual Category': y_test.values,
    'Predicted Category': y_pred
})

results_df.head(10)


#joblib.dump(model, 'url_category_model.pkl')

